language: php
php:
    - 5.6

script:
    - vendor/bin/tester tests -s -p php

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    - travis_retry composer install --no-interaction --prefer-dist
  
sudo: false

cache:
    directories:
        - $HOME/.composer/cache
